from typing import Optional

class Timeline:
    def __init__(self: Timeline) -> None: ...
    def __repr__(self: Timeline) -> str: ...
    @property
    def segment_count(self: Timeline) -> int: ...

class Project:
    def __init__(self: Project, *args, **kwargs) -> None: ...
    @property
    def name(self: Project) -> str: ...

def current_project() -> Optional[Project]: ...

timeline: Timeline
