[book]
authors = ["ScriptExec"]
language = "en"
multilingual = false
src = "src"
title = "VideoTagger Documentation"

[build]
create-missing = false
build-dir = "build"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"