name: Deploy Documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Runner VT_VERSION
        run: |
          chmod +x ./scripts/linux-runner-setup-docs.sh
          ./scripts/linux-runner-setup-docs.sh

      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@1.9.8
        with:
          working-directory: 'docs/'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Save documentation
        run: |
          mkdir -p /tmp/new_docs
          cp -r build/docs/public/* /tmp/new_docs/

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Copy docs to working directory
        run: |
          cp -r /tmp/new_docs/* .

      - name: Update version selector
        run: |
          python3 ./scripts/setup_docs_version_selector.py

      - name: Deploy to GitHub Pages
        uses: EndBug/add-and-commit@v9
        with:
          add: --all
          author_name: VideoTagger Docs
          message: Deployed documentation
