name: Deploy Documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup runner
        run: |
          chmod +x ./scripts/linux-runner-setup-docs.sh
          ./scripts/linux-runner-setup-docs.sh

      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@1.9.8
        with:
          working-directory: 'docs/'

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Save documentation
        run: |
          mkdir -p /tmp/new_docs
          cp -r build/docs/public/* /tmp/new_docs/

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy files to working directory
        run: |
          mkdir -p ./gh-pages/scripts
          cp ./VERSION ./gh-pages/
          cp ./scripts/docs.py ./gh-pages/scripts/
          cp ./scripts/setup_docs_version_selector.py ./gh-pages/scripts/
          mkdir -p ./gh-pages/scripts/docs/src
          cp ./docs/src/version_selector.html ./gh-pages/scripts/docs/src/
          cp -r /tmp/new_docs/* ./gh-pages/

      - name: Update version selector
        run: |
          cd gh-pages
          python3 ./scripts/setup_docs_version_selector.py
          rm -f ./VERSION
          rm -rf scripts
          rm -rf docs/src

      - name: Deploy to GitHub Pages
        uses: EndBug/add-and-commit@v9
        with:
          cwd: ./gh-pages
          add: --all
          author_name: VideoTagger Docs
          message: Deployed documentation
