name: Build With Premake
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Restore Premake Cache
        uses: actions/cache@v3
        with:
          path: .premake-build/build/bootstrap/
          key: premake5-${{ runner.os }}-${{ hashFiles('.premake-build/build/bootstrap/*') }}
          restore-keys: |
            premake5-${{ runner.os }}-
      
      - name: Installing premake5
        uses: Jarod42/install-premake5@v2
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Packages
        uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: build-essential libsdl2-dev ffmpeg libgtk-3-dev

      - name: run premake5
        run: premake5 gmake2

      - name: build
        run: |
            make config=shipping_x86_64
