name: Build With Premake
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
env:
  premake_version: v5.0.0-beta3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Restore Premake Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: .premake-build
          key: premake5-${{ runner.os }}-${{ env.premake_version }}
      
      - name: Installing premake5
        if: steps.cache.outputs.cache-hit != 'true'
        uses: Jarod42/install-premake5@v2
        with:
          ref: v5.0.0-beta3
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Package Repository
        run: |
          sudo add-apt-repository ppa:savoury1/ffmpeg5
      - name: Setup Packages
        uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: build-essential pkg-config libsdl2-dev libavcodec-dev libavformat-dev libswscale-dev libgtk-3-dev

      - name: run premake5
        run: premake5 gmake2

      - name: build
        run: |
            make config=shipping_x86_64
