name: Build With Premake
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Restore Premake Cache
        uses: actions/cache@v3
        with:
          path: ~/.premake5
          key: premake5-${{ runner.os }}-${{ hashFiles('.premake-build/build/bootstrap/*') }}
          restore-keys: |
            premake5-${{ runner.os }}-
      
      - name: Check if Premake exists
        id: check-premake
        run: |
          if [ ! -f ~/.premake5/premake5 ]; then
            echo "premake_needs_install=true" >> $GITHUB_ENV
          else
            echo "premake_needs_install=false" >> $GITHUB_ENV
          fi

      - name: Installing premake5
        if: ${{ env.premake_needs_install == 'true' }}
        uses: Jarod42/install-premake5@v2
      
      - name: Setup Packages
        run: |
            sudo apt-get install -y build-essential libsdl2-dev ffmpeg software-properties-common
            sudo add-apt-repository ppa:deadsnakes/ppa
            sudo apt-get install -y python3.12

      - name: run premake5
        run: premake5 gmake2

      - name: build
        run: |
            make config=shipping_x86_64
